./os os_0_mlq_paging  > output_actual/os_0_mlq_paging.actual.output
./os os_1_mlq_paging > output_actual/os_1_mlq_paging.actual.output
./os os_2_mlq_paging > output_actual/os_2_mlq_paging.actual.output
./os os_1_mlq_paging_small_1K > output_actual/os_1_mlq_paging_small_1K.actual.output
./os os_1_mlq_paging_small_4K > output_actual/os_1_mlq_paging_small_4K.actual.output
./os os_1_singleCPU_mlq > output_actual/os_1_singleCPU_mlq.actual.output
./os os_1_singleCPU_mlq_paging > output_actual/os_1_singleCPU_mlq_paging.actual.output
./os os_2_singleCPU_mlq_paging > output_actual/os_2_singleCPU_mlq_paging.actual.output
./os sched > output_actual/sched.actual.output
./os sched_0 > output_actual/sched_0.actual.output
./os sched_1 > output_actual/sched_1.actual.output
./os os_sc > output_actual/os_sc.actual.output
./os os_syscall > output_actual/os_syscall.actual.output
./os os_syscall_list > output_actual/os_syscall_list.actual.output